### ISSUE TITLE
Custom Parameters to Send HTTP request add-on

### ISSUE THREAD

**Issue by korsasub** [brendancooper/ta_http_action#2]
Hi,

Firstly,thank you for your work!.

We are migrating Splunk from 7.3.0 to 8.1. We have been using this plugin in some alerts and we are trying to move all the old actions(POST HTTP Request) to the new version of the add-on.
We are using "REST alert action" version 1.1.0 nowadays and we want to migrate to the newest version of the add-on "HTTP Alert Action" version 8.1.0 . We have done several test and we are not able to pass custom parameters from Splunk search to the "Send HTTP request" add-on. Could you provide any example?

Thanks for your support. Regards.

**Comment by brendancooper** [comment]
Hi,

Can you please either attach pictures of the Alert Config from the UI or paste your savedsearches.conf for that alert.
There were significant changes with the 8.1 update, notable the move to using $token$ instead of {field}

**Comment by korsasub** [comment]
Hi,

Thanks for your help.

I copy and paste savedsearch.conf from old app and the new one where i´m adapting the alert actions for the new APP.

**Splunk 7.3.0 + Rest Alert API**

[Alert: Old APP Version]
action.email = 1
action.email.include.results_link = 0
action.email.include.view_link = 0
action.email.inline = 1
action.email.message.alert = User blocked
action.email.sendresults = 1
action.email.subject.alert = $name$
action.email.useNSSubject = 1
action.keyindicator.invert = 0
action.logevent = 1
action.logevent.param.event = fecha=$result.firsttime$|user_id=$result.user_id$|dispositivo=$result.dispositivo$|ip=$result.ip$|isp=$result.isp$|country=$result.country$|region=$result.region$|agent=$result.agent$
action.logevent.param.host = localhost
action.logevent.param.index = index-general
action.makestreams.param.verbose = 0
action.nbtstat.param.verbose = 0
action.notable.param.verbose = 0
action.nslookup.param.verbose = 0
action.ping.param.verbose = 0
action.risk.param.verbose = 0
action.send2uba.param.verbose = 0
action.send_custom_rest_request = 1
action.send_custom_rest_request.param.custom_headers = SOAPAction="opTestParam"
action.send_custom_rest_request.param.endpoint = https://example.free.beeceptor.com
action.send_custom_rest_request.param.ingestion_safety_max_size = 600
action.send_custom_rest_request.param.payload = <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v01="https://example.free.beeceptor.com">     <soapenv:Header/>     <soapenv:Body>        <v01:BewebRequest>           <v01:CAB>              <v01:CAJ>70</v01:CAJ>              <v01:OPE>26</v01:OPE>           </v01:CAB>           <v01:DAT>              <v01:CLI>{user_id}</v01:CLI>                            <v01:MEN>Device {dispositivo} </v01:MEN>           </v01:DAT>        </v01:BewebRequest>     </soapenv:Body>  </soapenv:Envelope>
action.send_custom_rest_request.param.response_index = index-general
action.threat_add.param.verbose = 0
alert.digest_mode = 0
alert.severity = 1
alert.suppress = 1
alert.suppress.fields = user_id
alert.suppress.period = 24h
alert.track = 1
counttype = number of events
cron_schedule = */2 * * * *
dispatch.earliest_time = -24h@h
dispatch.latest_time = now
display.events.fields = ["host","source","sourcetype","QUERY","src","site","http_method","http_referer","log_subtype","severity","signature","src_ip","app:technology","category","dest_category","vendor_action","dest","EventCode","event_id","cs_url_host","application","dest_port","app","user","recipient","sender","threat","status","index","rule","Caller_Computer_Name","x_wbrs_threat_type","dvc","dvc_name","x_amp_sha","hip_name","os","action","dest_name","cs_uri_stem","Logon_Account","PARAM1","PARAM2","PARAM3","PARAM4","mailfrom","sourceHostName","deviceExternalId","duser","deviceInboundInterface","ESASPFVerdict","bytes_out","bytes_in","Keywords"]
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.charting.chart = line
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=index-general (( "Device Anomalies" AND "Network Anomalies 42") AND ("Suspicious Behavior" OR "Unknown device" )) earliest=-40m latest=-1m | rename "session.alerts{}.extra.signature_name" as signature "session.alerts{}.type" as type "session.user_id" as user_id "session.device.device_type" as dispositivos | stats first(_time) as firstepoch last(_time) as lastepoch values(type) as alertas values(dispositivos) as dispositivo values(IP) as ip values(ISP) as isp values(country) as country values(session.network.region) as region values(session.device.user_agent) as agent count as number by user_id | eval firsttime = strftime(firstepoch, "%Y-%m-%d %H:%M:%S")  | eval lasttime = strftime(lastepoch, "%Y-%m-%d %H:%M:%S")

**Splunk 8.1 + HTTP Alert Action**

[Alert: New APP Version]
action.httpalert = 1
action.httpalert.param.custom_headers = SOAPAction="opTestParam"
action.httpalert.param.endpoint = https://example.free.beeceptor.com
action.httpalert.param.method = post
action.httpalert.param.payload = <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v01="https://example.free.beeceptor.com">     <soapenv:Header/>     <soapenv:Body>        <v01:BewebRequest>           <v01:CAB>              <v01:CAJ>70</v01:CAJ>              <v01:OPE>26</v01:OPE>           </v01:CAB>           <v01:DAT>              <v01:CLI>$usuario$</v01:CLI>                            <v01:MEN>This is a test message with param </v01:MEN>           </v01:DAT>        </v01:BewebRequest>     </soapenv:Body>  </soapenv:Envelope>
action.syslog = 0
alert.digest_mode = 0
alert.severity = 1
alert.suppress = 0
alert.suppress.period = 60s
alert.track = 1
counttype = number of events
cron_schedule = */5 * * * *
description = Test Alert POST Http
dispatch.earliest_time = -15m
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
enableSched = 1
quantity = 0
relation = greater than
request.ui_dispatch_app = search
request.ui_dispatch_view = search
search = index=_audit action="login attempt" info=failed | rename user as usuario "session.user_id" as user_id | table usuario

Thank you.

**Comment by brendancooper** [comment]
We use Splunk token substitution so it's not as simple as just replacing {} with $ $.
Have a look at https://docs.splunk.com/Documentation/Splunk/latest/Alert/EmailNotificationTokens
So instead of $usuario$ it should be $result.usuario$

Let me know if that fixes it

**Comment by korsasub** [comment]
Hi,

Sorry for the delay. Thanks for your support.
I have done a test alert on splunk and apparently seems working. I have to change some more if i have error i will let you know.
Thank you. Regards.
